basicapp/urls.py
from django.urls import path
from basicapp import views


app_name='basicapp'
urlpatterns = [

    path('register/',views.register,name='register'),
    path('login/',views.user_login,name="user_login"),


]

basicforms/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),
    path('logout/',views.user_logout,name="logout"),
    path('special/',views.special,name='special')
]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo



class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')      

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):

    return render(request,'basicapp/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")



@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basicapp/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:register' %}">REGISTER</a></li>


          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
          {% endif   %}
        </ul>
      </div>
    </nav>
    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>

{% extends "basicapp/base.html" %}
 {% block body_block %}

 <div class="jumbotron">
   <h1>Django LEvel 5</h1>


 </div>

 {% endblock %}

templates/basicapp/login.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
 {% block body_block %}

 <div class="jumbotron">
   <h1>please login</h1>
   <form  action="{% url 'basicapp:user_login' %}" method="post">
     {% csrf_token %}
     <label for="username">Username:</label>
     <input type="text" name="username" placeholder="enter username">

     <label for="password">Password:</label>
     <input type="text" name="password">


     <input type="submit" value="Login">

   </form>

 </div>

 {% endblock %}

templates/basicapp/register.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thanks for registering</h1>
  {% else %}
    <h3>Register!</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
     {{user_form.as_p}}
     {{profile_form.as_p}}
     <input type="submit" name="" value="Register">
     </form>
  {% endif %}

</div>

{% endblock %}